"""Export utilities — PDF (WeasyPrint), PNG (Kaleido), CSV (Pandas)."""

from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional

import pandas as pd
import plotly.io as pio

from app.infrastructure.adapters.storage import get_exports_dir


def export_pdf(
    tenant_id: str,
    job_id: str,
    question: str,
    executive_summary: str,
    insight_report: str,
    recommendations: List[Dict[str, Any]],
) -> str:
    """Render an analysis report as a PDF and return the file path.

    Uses WeasyPrint to convert styled HTML to PDF.
    """
    exports_dir = get_exports_dir(tenant_id)
    file_path = str(exports_dir / f"report_{job_id}.pdf")

    # Build HTML report
    recs_html = ""
    for i, rec in enumerate(recommendations, 1):
        recs_html += f"""
        <div class="rec">
            <h3>Recommendation {i}</h3>
            <p><strong>Action:</strong> {rec.get('action', 'N/A')}</p>
            <p><strong>Expected Impact:</strong> {rec.get('expected_impact', 'N/A')}</p>
            <p><strong>Confidence:</strong> {rec.get('confidence_score', 'N/A')}%</p>
            <p><strong>Main Risk:</strong> {rec.get('main_risk', 'N/A')}</p>
        </div>
        """

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; color: #333; }}
            h1 {{ color: #1a73e8; border-bottom: 2px solid #1a73e8; padding-bottom: 10px; }}
            h2 {{ color: #555; margin-top: 30px; }}
            .summary {{ background: #f0f4ff; padding: 20px; border-radius: 8px; margin: 20px 0; }}
            .rec {{ background: #fafafa; padding: 15px; border-left: 4px solid #1a73e8;
                    margin: 10px 0; border-radius: 0 8px 8px 0; }}
            .question {{ font-style: italic; color: #666; font-size: 1.1em; }}
            .footer {{ margin-top: 40px; padding-top: 10px; border-top: 1px solid #ddd;
                       font-size: 0.85em; color: #999; }}
        </style>
    </head>
    <body>
        <h1>Analysis Report</h1>
        <p class="question">Question: {question}</p>

        <h2>Executive Summary</h2>
        <div class="summary">{executive_summary}</div>

        <h2>Detailed Analysis</h2>
        <div>{insight_report}</div>

        <h2>Recommendations</h2>
        {recs_html if recs_html else "<p>No recommendations available.</p>"}

        <div class="footer">
            Generated by Autonomous Data Analyst Agent
        </div>
    </body>
    </html>
    """

    try:
        from weasyprint import HTML
        HTML(string=html_content).write_pdf(file_path)
    except ImportError:
        # Fallback: write HTML if WeasyPrint is not installed
        html_path = file_path.replace(".pdf", ".html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        return html_path

    return file_path


def export_png(
    tenant_id: str,
    job_id: str,
    chart_json: Dict[str, Any],
) -> str:
    """Render a Plotly chart as a PNG image and return the file path."""
    exports_dir = get_exports_dir(tenant_id)
    file_path = str(exports_dir / f"chart_{job_id}.png")

    fig = pio.from_json(json.dumps(chart_json))
    fig.write_image(file_path, format="png", width=1200, height=800, scale=2)

    return file_path


def export_csv(
    tenant_id: str,
    job_id: str,
    chart_json: Optional[Dict[str, Any]],
) -> str:
    """Extract data from chart JSON and save as CSV.

    Falls back to an empty CSV if no data is available.
    """
    exports_dir = get_exports_dir(tenant_id)
    file_path = str(exports_dir / f"data_{job_id}.csv")

    if chart_json and "data" in chart_json:
        # Extract data from the first trace
        traces = chart_json["data"]
        if traces:
            trace = traces[0]
            df_data: Dict[str, Any] = {}
            if "x" in trace:
                df_data["x"] = trace["x"]
            if "y" in trace:
                df_data["y"] = trace["y"]
            if "labels" in trace:
                df_data["labels"] = trace["labels"]
            if "values" in trace:
                df_data["values"] = trace["values"]
            if df_data:
                df = pd.DataFrame(df_data)
                df.to_csv(file_path, index=False)
                return file_path

    # Fallback
    pd.DataFrame().to_csv(file_path, index=False)
    return file_path
